// ─────────────────────────────────────────────────────────────────────────────
// History → Excel export.
//
// Two flavours:
//   - `exportPoToWorkbook(rec)`  → workbook with the full detail of one PO
//                                  (overview, products, DCs, Sierra matrix /
//                                  Burlington lines, BOL summary)
//   - `exportPoListToWorkbook(records)`
//                                → single-sheet workbook listing every PO
// ─────────────────────────────────────────────────────────────────────────────

import * as XLSX from "xlsx";
import type {
  BurlingtonShipment,
  PoRecord,
  SierraShipment,
} from "./types";

function fmtDate(iso?: string | null): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString();
}

/** Trigger a browser download of an XLSX workbook. */
export function downloadWorkbook(wb: XLSX.WorkBook, filename: string): void {
  XLSX.writeFile(wb, filename);
}

/** Sheet listing every PO at a glance — what most users want when they
 *  click "Export all". */
export function exportPoListToWorkbook(records: PoRecord[]): XLSX.WorkBook {
  const rows = records.map((r) => ({
    "PO Number": r.po_number,
    Brand: r.brand,
    "Generated By": r.created_by_username ?? "",
    "Generated On": fmtDate(r.created_at),
    Labels: r.label_total ?? 0,
    Pallets: r.total_pallets ?? 0,
    "BOL #": r.bol_number ?? "",
    Updated: fmtDate(r.updated_at),
    Products: r.shipment_state?.products?.join(", ") ?? "",
    DCs:
      r.shipment_state?.dcs?.map((d) => `${d.num} ${d.code}`).join(", ") ?? "",
  }));
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "PO History");
  return wb;
}

function buildOverviewSheet(rec: PoRecord): XLSX.WorkSheet {
  const rows: Array<[string, string | number]> = [
    ["PO Number", rec.po_number],
    ["Brand", rec.brand],
    ["Generated By", rec.created_by_username ?? ""],
    ["Generated On", fmtDate(rec.created_at)],
    ["Updated", fmtDate(rec.updated_at)],
    ["BOL #", rec.bol_number ?? ""],
    ["Total Labels", rec.label_total ?? 0],
    ["Total Pallets", rec.total_pallets ?? 0],
  ];
  return XLSX.utils.aoa_to_sheet([["Field", "Value"], ...rows]);
}

function buildProductsSheet(rec: PoRecord): XLSX.WorkSheet {
  const products = rec.shipment_state?.products ?? [];
  return XLSX.utils.aoa_to_sheet([
    ["#", "Product"],
    ...products.map((p, i) => [i + 1, p]),
  ]);
}

function buildDcsSheet(rec: PoRecord): XLSX.WorkSheet {
  const dcs = rec.shipment_state?.dcs ?? [];
  return XLSX.utils.aoa_to_sheet([
    ["#", "DC Num", "Code", "Name", "Street", "City/State/Zip"],
    ...dcs.map((d, i) => [i + 1, d.num, d.code, d.name, d.street, d.city]),
  ]);
}

function buildQtyMatrixSheet(rec: PoRecord): XLSX.WorkSheet | null {
  const products = rec.shipment_state?.products ?? [];
  const dcs = rec.shipment_state?.dcs ?? [];
  const qty = rec.shipment_state?.qty ?? {};
  if (!products.length || !dcs.length) return null;
  const header = ["Product", ...dcs.map((d) => `${d.code} (${d.num})`), "Total"];
  const rows = products.map((p) => {
    const row: Array<string | number> = [p];
    let total = 0;
    dcs.forEach((d) => {
      const v = (qty[p] && qty[p][d.num]) || 0;
      row.push(v);
      total += v;
    });
    row.push(total);
    return row;
  });
  return XLSX.utils.aoa_to_sheet([header, ...rows]);
}

function buildSierraSheet(s: SierraShipment): XLSX.WorkSheet {
  const dcs = s.dcs ?? [];
  const header: string[] = ["#", "Product"];
  dcs.forEach((d) => header.push(`Orig ${d.code} (units)`));
  header.push("Orig Cases", "Orig Units");
  dcs.forEach((d) => header.push(`Final ${d.code} (cases)`));
  header.push("Final Cases", "Final Units");
  header.push("Cu ft / case");
  dcs.forEach((d) => header.push(`Cu ft ${d.code}`));

  const rows: Array<Array<string | number>> = [header];
  (s.lines ?? []).forEach((l, i) => {
    let origUnits = 0,
      finalCases = 0;
    const row: Array<string | number> = [i + 1, l.product || ""];
    dcs.forEach((d) => {
      const v = typeof l.orig?.[d.num] === "number" ? (l.orig[d.num] as number) : 0;
      row.push(v);
      origUnits += v;
    });
    row.push(origUnits / 10, origUnits);
    dcs.forEach((d) => {
      const v = typeof l.final?.[d.num] === "number" ? (l.final[d.num] as number) : 0;
      row.push(v);
      finalCases += v;
    });
    row.push(finalCases, finalCases * 10);
    row.push("");
    dcs.forEach(() => row.push(""));
    rows.push(row);
  });
  return XLSX.utils.aoa_to_sheet(rows);
}

function buildBurlingtonSheet(b: BurlingtonShipment): XLSX.WorkSheet {
  const header = [
    "#",
    "PO",
    "Product",
    "Orig Qty",
    "Final Qty",
    "Hi",
  ];
  const rows: Array<Array<string | number>> = [header];
  (b.lines ?? []).forEach((l, i) => {
    rows.push([
      i + 1,
      l.po ?? "",
      l.product || "",
      typeof l.origQty === "number" ? l.origQty : "",
      typeof l.finalQty === "number" ? l.finalQty : "",
      typeof l.hi === "number" ? l.hi : "",
    ]);
  });
  // Pallet constants + header
  rows.push([]);
  rows.push(["Header PO", b.headerPo ?? ""]);
  rows.push(["Start Date", b.startDate ?? ""]);
  rows.push(["End Date", b.endDate ?? ""]);
  rows.push(["Pallet Cu ft", b.palletConstants?.cuFt ?? ""]);
  rows.push(["Pallet wt (lb)", b.palletConstants?.wt ?? ""]);
  rows.push(["Max Pallet Height (in)", b.palletConstants?.maxHeight ?? ""]);
  return XLSX.utils.aoa_to_sheet(rows);
}

function buildBolSheet(rec: PoRecord): XLSX.WorkSheet | null {
  const b = rec.bol_form;
  if (!b) return null;
  const fields: Array<[string, string]> = [
    ["BOL Number", b.bol_number ?? ""],
    ["BOL PO #", b.bol_po_number ?? ""],
    ["Load ID", b.load_id ?? ""],
    ["Auth #", b.auth_num ?? ""],
    ["Freight Terms", b.freight_terms ?? ""],
    ["Ship-From Name", b.sf_name ?? ""],
    ["Ship-From Address", b.sf_address ?? ""],
    ["Ship-From CSZ", b.sf_csz ?? ""],
    ["Ship-To Name", b.st_name ?? ""],
    ["Ship-To Location", b.st_location ?? ""],
    ["Ship-To Address", b.st_address ?? ""],
    ["Ship-To CSZ", b.st_csz ?? ""],
    ["Carrier", b.carrier_name ?? ""],
    ["SCAC", b.scac ?? ""],
    ["Pro #", b.pro_number ?? ""],
    ["Trailer #", b.trailer_number ?? ""],
    ["Seal #", b.seal_number ?? ""],
    ["Commodity", b.commodity ?? ""],
    ["NMFC", b.nmfc ?? ""],
    ["LTL Class", b.ltl_class ?? ""],
    ["Handling Unit Qty", b.hu_qty ?? ""],
    ["Handling Unit Type", b.hu_type ?? ""],
    ["Package Qty", b.hu_pkg_qty ?? ""],
    ["Package Type", b.hu_pkg_type ?? ""],
    ["Weight (lb)", b.hu_weight ?? ""],
  ];
  return XLSX.utils.aoa_to_sheet([["Field", "Value"], ...fields]);
}

/** Detailed per-PO workbook. Includes brand-specific sheets where applicable. */
export function exportPoToWorkbook(rec: PoRecord): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, buildOverviewSheet(rec), "Overview");
  XLSX.utils.book_append_sheet(wb, buildProductsSheet(rec), "Products");
  XLSX.utils.book_append_sheet(wb, buildDcsSheet(rec), "DCs");
  const qtyWs = buildQtyMatrixSheet(rec);
  if (qtyWs) XLSX.utils.book_append_sheet(wb, qtyWs, "Quantities");
  const sierra = rec.shipment_state?.sierra;
  if (sierra) XLSX.utils.book_append_sheet(wb, buildSierraSheet(sierra), "Sierra Matrix");
  const burl = rec.shipment_state?.burlington;
  if (burl) XLSX.utils.book_append_sheet(wb, buildBurlingtonSheet(burl), "Burlington Lines");
  const bolWs = buildBolSheet(rec);
  if (bolWs) XLSX.utils.book_append_sheet(wb, bolWs, "BOL");
  return wb;
}
