-- ─────────────────────────────────────────────────────────────────────────────
-- QuikT Tool — Supabase schema
-- Run this in the Supabase Dashboard → SQL Editor (one time, on a fresh project).
-- ─────────────────────────────────────────────────────────────────────────────

-- One row per PO. Holds the full Routing + Label Format + BOL snapshot so the
-- whole shipment can be recalled by PO number months later. Saving the same PO
-- again upserts (updates) the existing row.
create table if not exists public.po_records (
  id              uuid primary key default gen_random_uuid(),
  po_number       text not null,
  po_digits       text not null,                 -- trailing digit group, used for search
  brand           text not null,                 -- 'homegoods' | 'tjx' | 'marshalls'
  shipment_state  jsonb not null default '{}'::jsonb,  -- products, dcs, qty, qtyFinalTotal, skuMeta...
  label_format    jsonb not null default '{}'::jsonb,
  bol_form        jsonb not null default '{}'::jsonb,
  summary         jsonb,                         -- computed per-DC summary + totals
  label_total     integer not null default 0,    -- total carton labels (for the list view)
  total_pallets   integer not null default 0,
  bol_number      text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  created_by      uuid references auth.users (id) on delete set null,
  -- Username captured at save time so the History tab can show "generated by"
  -- without joining auth.users (which is not directly queryable from the client).
  created_by_username text
);

-- Migration for existing installs: add the new column if missing.
alter table public.po_records
  add column if not exists created_by_username text;


-- ─────────────────────────────────────────────────────────────────────────────
-- SKU Master — central catalogue of every SKU.
-- Column layout matches the existing "SKU MASTER.xlsx" workbook used by the
-- Quikfoods team: Item meta + per-unit / per-case / per-pallet dimensions
-- and weights. Powers the spreadsheet-style tab + Excel import/export.
-- Keyed by item_code (case-insensitive unique).
-- ─────────────────────────────────────────────────────────────────────────────

-- Safe to drop+recreate: this table has no production data yet.
drop table if exists public.sku_master cascade;

create table public.sku_master (
  id                       uuid primary key default gen_random_uuid(),

  -- ── Item identity ──
  -- UNIQUE (not just a unique index) so upsert(onConflict:'item_code') works.
  -- Case-insensitivity is enforced at the app layer (item_code is uppercased
  -- before saving in src/lib/skuMaster.ts → normalise()).
  item_code                text not null unique,
  item_description         text,
  group_name               text,
  sub_group                text,
  case_pack                integer,

  -- ── Unit net weight ──
  unit_net_wt_g            numeric,
  unit_net_wt_oz           numeric,
  unit_net_wt_lb           numeric,

  -- ── Carton net weight ──
  carton_net_wt_kg         numeric,
  carton_net_wt_lb         numeric,

  -- ── UPC / GTIN codes (text to preserve leading zeros) ──
  gtin_upc_case_code       text,
  unit_upc_code            text,

  -- ── Misc unit info ──
  shelf_life_months        numeric,

  -- ── Unit dimensions (inches) ──
  unit_height_in           numeric,
  unit_length_in           numeric,
  unit_width_in            numeric,
  unit_gross_wt_g          numeric,
  unit_gross_wt_oz         numeric,

  -- ── Case ──
  case_cube_cuft           numeric,
  case_height_in           numeric,
  case_length_in           numeric,
  case_width_in            numeric,
  case_gross_wt_lb         numeric,
  case_gross_wt_kg         numeric,

  -- ── Pallet ──
  pallet_length_in         numeric,
  pallet_width_in          numeric,
  pallet_height_in         numeric,
  pallet_ti                integer,
  pallet_hi                integer,
  pallet_cases_per_pallet  integer,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid references auth.users (id) on delete set null,
  created_by_username      text
);

create index if not exists sku_master_updated_at_idx
  on public.sku_master (updated_at desc);

drop trigger if exists sku_master_set_updated_at on public.sku_master;
create trigger sku_master_set_updated_at
  before update on public.sku_master
  for each row execute function public.set_updated_at();

alter table public.sku_master enable row level security;

drop policy if exists "authenticated full access" on public.sku_master;
create policy "authenticated full access"
  on public.sku_master
  for all
  to authenticated
  using (true)
  with check (true);

-- A PO is unique per brand (the same digits could theoretically appear under
-- different retailers). Upserts target this constraint.
create unique index if not exists po_records_po_brand_uniq
  on public.po_records (po_number, brand);

-- Fast lookup when the user types just the PO digits into the search box.
create index if not exists po_records_po_digits_idx on public.po_records (po_digits);
create index if not exists po_records_updated_at_idx on public.po_records (updated_at desc);

-- Keep updated_at fresh on every write.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists po_records_set_updated_at on public.po_records;
create trigger po_records_set_updated_at
  before update on public.po_records
  for each row execute function public.set_updated_at();

-- ── Row Level Security ──
-- This is an internal tool: any signed-in (authenticated) user has full access.
alter table public.po_records enable row level security;

drop policy if exists "authenticated full access" on public.po_records;
create policy "authenticated full access"
  on public.po_records
  for all
  to authenticated
  using (true)
  with check (true);
